### ISSUE TITLE
Love these switches

### ISSUE THREAD

**Issue by C1ARKGABLE** [riskable/void_switch#1]
Saw [this YouTube video](https://www.youtube.com/watch?v=H_Ym9528awM) and had to find where I could get these switches. I'd love to try printing a low profile set.

Have you thought about potentially adding elector magnets to tune the key characteristics on the fly?

Keep up the great work

**Comment by C1ARKGABLE** [comment]
Not an issue, just wanted to comment

**Comment by riskable** [comment]
Haha I made this repo *in preparation* for releasing my switch files.  They're not quite ready yet.  Very soon though :smile:
