### ISSUE TITLE
Switch tends to stick when bottomed out

### ISSUE THREAD

**Issue by JBP113** [riskable/void_switch#11]
I have all of the magnets in properly and I have found on my test switch before I print anymore of them that the switch has a tendency to stay down sometimes, any tips?

**Comment by RussNelson** [comment]
Are you sure you have the magnet polarity correct? The top pair should repel and the bottom pair should attract.

**Comment by JBP113** [comment]
I had them correct, I didn't realize my print came out rough so there was to much friction.
