### ISSUE TITLE
Question: how is your PCB/circuit?

### ISSUE THREAD

**Issue by ianliu** [riskable/void_switch#5]
Hi Riskable,

First I would like to say: MOTHER F*#$%! GENIUS design! Congrats!

Second, how is your circuit implemented? Do you need a matrix of analog pins for this keyboard to work? Is it even possible to make an analog matrix?

How do you measure each key? Is there a coil under each key?

Thanks!

**Comment by RussNelson** [comment]
There is no Matrix unless you use Reed switches. If you use hall effect
sensors, there is one for key, and you need one bit of IO per key.

**Comment by DeadlySurgeon** [comment]
Any idea what hall effect sensors would be good to use? I looked at the kicad repo and there doesn't seem to be any recommendations.

**Comment by RussNelson** [comment]
https://www.amazon.com/gp/product/B09PG3PGH6/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1

**Comment by DeadlySurgeon** [comment]
@RussNelson Those are THC. Any clues on SMDs, like in the example board repo?

**Comment by riskable** [comment]
For my boards I've mostly been using OH49E-S hall effect sensors.  They're cheap and readily available.

Also note that I'm making a tutorial series talking about how to make your own analog keyboard PCB (parts 1 and 2 are up): https://youtu.be/TfKz_FbZWLQ

**Comment by udif** [comment]
Looking at https://github.com/riskable/void_switch_kicad/blob/main/symbols/49e.kicad_sym I see you also found:

https://lcsc.com/product-detail/Magnetic-Sensors_GoChip-Elec-Tech-Shanghai-GH39FKSW_C266230.html
It seems to be ~30% cheaper, at 0.1306$/unit (150PCS) vs 0.1984$/unit (100PCS).

Comparing the datasheet, it seems to have a compatible pinout, but it is slightly less sensitive (1.8mv/GS vs 2mV/GS for OH49E-S), and typically consume 6mA vs 4.2mA for the OH49E-S, which might be an issue in a keyboard with close to 100 switches, esp. if you want to power it from USB.

Do you have any actual experience with this part?

**Comment by riskable** [comment]
@udif Yes, I swap out OH49E-S for GH39FKSW based on what's available all the time.  My firmware doesn't really care much about the sensitivity and both are approximately using the same amount of power when powered at 3.3V.
