### ISSUE TITLE
Sheath does not appear to fit into body on default settings

### ISSUE THREAD

**Issue by Exxion** [riskable/void_switch#6]
I was excited to try these keys out (and still am), but when I printed one up, the sheath did not even come close to snapping into the body, even after considerable filing and use of pliers. I tried again (with the recommended layer height this time) and got the same result. Then I checked out the render in OpenSCAD, and found that at the default settings, it shows a considerable negative clearance between the sheath's magnet holder and the body's pocket for it. The clearance around that part does not appear to become positive until the sheath tolerance setting is around 0.4. Am I doing something wrong, or did an error make its way into the final files?
I'm confident in the quality of my printer, though somewhat less confident in the quality of my filament.

**Comment by RussNelson** [comment]
I was able to print a key from the supplied .STL files. I have 4x1.7 magnets.

**Comment by Exxion** [comment]
And the sheath snapped all the way in, with the sheath's magnet holder inside a pocket in the body? I just measured the provided STL file, and the hole the sheath is supposed to fit into is ~0.15mm shorter than the sheath, along the axis through the center of the magnet holder and the opposite corner of the body, not counting the notch on the side of the hole opposite the magnet holder.

**Comment by RussNelson** [comment]
Well, here's the thing: I printed both the 4x2 magnet STL and 4x1.7 magnet STLs, then didn't keep track of which ones I was assembling. :-1: However, that only changes the thickness of the magnet holder, which shouldn't affect the dimensions of the sheath or body.

**Comment by Exxion** [comment]
Yeah, that shouldn't change anything as far as this goes.
My filament indeed wasn't very good, and switching to a better filament improved the situation slightly, but there's still no way it would fit for me without either setting that 8 to 64 or greatly increasing the sheath tolerance. Using the better filament *and* setting the 8 to 64 made it very nearly possible. Close enough that at that point the remaining issue is almost certainly on my end.

**Comment by riskable** [comment]
It's supposed to be nice and tight.  That's why I have a picture of me using pliers to press the two together.  You should still be able to do it by hand though.  I've printed thousands of these things and never had a problem.  You can change line 208 in body.scad from `fn = sheath_inside_body ? 64 : 8;` to just `fn = 64;` if you want a looser fit.

**Comment by masterjuggler** [comment]
It helped me to tilt the sheath down slightly toward the round part to press that in first. Occasionally I had to chamfer the edge to get it started, but once it starts going in it'll snap into place with pliers. I made a tester batch of a bunch of different actuation weights and stroke lengths that way.

**Comment by Exxion** [comment]
I dried out my filament and it fit, albeit not easily. I'm surprised it fits together with that much negative clearance in the STL! Regardless, apologies for the trouble.
